export const categories = [
  "World News",
  "Politics",
  "Business",
  "Technology",
  "Health",
  "Sports",
  "Culture",
  "Podcast",
];

export const blockedDomains = [
  "washingtonpost.com",
  "cnn.com",
  "bloomberg.com",
  "nytimes.com",
  "nbcboston.com",
  "nbcnews.com",
  "usatoday.com",
  "reuters.com",
  "people.com",
  "pagesix.com",
  "medicalxpress.com",
  "globalresearch.ca",
  "yahoo.com",
  "yahoo.co.uk",
  "ew.com",
  "fandom.com",
  "screenrant.com",
  "thegamer.com",
  "teslarati.com",
  "wsj.com",
  "gigazine.net",
];